Repository CMU-17313Q/nodebb-f24-elev8, pull requests merged in 2024-10, with the labels that each got.

#52 Refactored code to add Predefined quick reply feature in public/src/modules/quickreply.js
  public/src/modules/quickreply.js
Labels: backend, frontend

#53 Creating the "UserGuide.md" file in the root directory for user documentation
  UserGuide.md
  pidfile 6
  pidfile 7
Labels: documentation

#55 Refactored code to create suggested responses within the main reply feature in node_modules/nodebb-plugin-composer-default/static/lib/composer.js and /node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
Labels: backend, frontend

#58 Add automated testing for inappropriate words user story
  public/src/client/chats.js
  src/controllers/posts.js
  src/posts/create.js
  src/routes/index.js
  src/socket.io/plugins.js
  src/socket.io/posts.js
  src/views/partials/chats/message.tpl
  test/posts.js
Labels: backend, testing, SUB ISSUE

#44 Added extra emoji reactions in src/views/partials/chats/message.tpl and made style changes in public/scss/chats.scss
  src/views/partials/chats/message.tpl
Labels: enhancement, frontend, SUB ISSUE

#56 SUB ISSUE: Add automated tests for the anonymous feature
  test/topics.js
Labels: documentation, backend, testing

#62 Ran Plato Static Analysis Tool on public/src/client/topic/*.js
  plato_reports/files/change_owner_js/report.history.js
  plato_reports/files/change_owner_js/report.history.json
  plato_reports/files/delete_posts_js/report.history.js
  plato_reports/files/delete_posts_js/report.history.json
  plato_reports/files/diffs_js/report.history.js
  plato_reports/files/diffs_js/report.history.json
  plato_reports/files/events_js/report.history.js
  plato_reports/files/events_js/report.history.json
  plato_reports/files/fork_js/report.history.js
  plato_reports/files/fork_js/report.history.json
  plato_reports/files/images_js/report.history.js
  plato_reports/files/images_js/report.history.json
  plato_reports/files/merge_js/report.history.js
  plato_reports/files/merge_js/report.history.json
  plato_reports/files/move_js/report.history.js
  plato_reports/files/move_js/report.history.json
  plato_reports/files/move_post_js/report.history.js
  plato_reports/files/move_post_js/report.history.json
  plato_reports/files/postTools_js/report.history.js
  plato_reports/files/postTools_js/report.history.json
  plato_reports/files/posts_js/report.history.js
  plato_reports/files/posts_js/report.history.json
  plato_reports/files/replies_js/report.history.js
  plato_reports/files/replies_js/report.history.json
  plato_reports/files/tag_js/report.history.js
  plato_reports/files/tag_js/report.history.json
  plato_reports/files/threadTools_js/report.history.js
  plato_reports/files/threadTools_js/report.history.json
  plato_reports/files/votes_js/report.history.js
  plato_reports/files/votes_js/report.history.json
  plato_reports/report.history.js
  plato_reports/report.history.json
Labels: testing
