Repository CMU-17313Q/nodebb-f24-elev8, pull requests merged in 2024-09, with the labels that each got.

#30 added two helper functions in src/posts/create.js
  src/posts/create.js
Labels: backend, SUB ISSUE

#31 Replace inappropriate words with asterisks in src/posts/create.js to resolve bad word detection issue
  dump.rdb
  src/posts/create.js
Labels: enhancement, backend, frontend, SUB ISSUE

#34 Refactored code to allow display of anonymous posts in src/topics/posts.js & src/topics/teaser.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  src/posts/create.js
  src/topics/posts.js
  src/topics/teaser.js
  src/topics/tools.js
  test/api.js
Labels: backend, frontend, SUB ISSUE
